# Generated by Django 5.0.1 on 2024-01-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='title',
            field=models.CharField(default='Title', max_length=200),
        ),
    ]
