# Generated by Django 5.0.1 on 2024-01-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_tasks_description_tasks_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
